outputs:
  GPIOB_7: "Injector 8"
  GPIOB_8: "Injector 7"
  GPIOB_9: "Injector 2"
  GPIOE_0: "Injector 4"
  GPIOE_1: "Injector 3"
  GPIOE_2: "Injector 1"
  GPIOE_3: "Boost Valve"
  GPIOE_4: "Injector 6"
  GPIOE_5: "Injector 5"
  GPIOE_6: "Gp Out 4"
  GPIOE_15: "Trigger Error"
  GPIOD_1: "Coil 2"
  GPIOD_2: "Coil 1"
  GPIOD_4: "Coil 3"
  GPIOD_0: "Coil 4"
  GPIOD_3: "Coil 5"
  GPIOD_5: "Coil 6"
  GPIOD_9: "Gp Out 5"
  GPIOD_10: "Coolant Fan"
  GPIOD_11: "Brake Relay" 
  GPIOD_12: "AC Compressor"
  GPIOD_13: "Main Relay"
  GPIOD_14: "Fuel Pump" 
  GPIOG_2: "HS Out 4"
  GPIOG_3: "HS Out 3"
  GPIOG_4: "HS Out 2"
  GPIOG_5: "HS Out 1"
  GPIOG_6: "Coil 8"
  GPIOG_7: "Coil 7"
  GPIOG_10: "Gp Out 3"
  GPIOG_11: "VVT Intake"
  GPIOG_12: "VVt Exhaust"
  GPIOG_13: "Thermostat Control"
  GPIOG_14: "Gp Out 2"
  GPIOG_15: "Gp Out 1"
  
analog_inputs:
  EFI_ADC_0: "Vbat"
  EFI_ADC_1: "UR Wideband Sensor"
  EFI_ADC_2: "UA Wideband Sensor"
  EFI_ADC_3: "Coolant Temp 2"
  EFI_ADC_4: "Throttle Pedal Sub"
  EFI_ADC_5: "Throttle Pedal Main"
  EFI_ADC_6: "AN Volt 4"
  EFI_ADC_7: "Maf Sensor"
  EFI_ADC_8: "Intake Air Temp"
  EFI_ADC_9: "TPS Sub"
  EFI_ADC_10: "AN Volt 1"
  EFI_ADC_11: "AN Volt 3"
  EFI_ADC_12: "Map Sensor"
  EFI_ADC_13: "Coolant Temp"
  EFI_ADC_14: "AN Volt 2"
  EFI_ADC_15: "TPS Main"
  
  
event_inputs:
  GPIOD_15: "Crank Sensor"
  GPIOC_6: "Cam Sensor" 
  GPIOG_8: "Cam Sensor 2"
  GPIOC_7: "Speed Signal"
 

switch_inputs:
  GPIOF_14: "Brake Switch"
  GPIOF_15: "Clutch Switch"
  GPIOF_11: "Digital In 1"
  GPIOG_0: "Digital In 2"
  GPIOG_1: "Digital In 3"
  GPIOF_12: "Digital In 4"
  GPIOF_13: "Digital In 5"
  
  
  